### ISSUE TITLE
Gem contains opinionated guides

### ISSUE THREAD

**Issue by oleg-vinted** [rubyatscale/use_packwerk#17]
For this tool to be adopted widely, it needs to be generic enough to allow anyone to adapt to their needs. Right now, however, when moving files around, it will tell you to [about Slack channels](https://github.com/rubyatscale/use_packwerk/blob/3f36de7be61da43a27c6079874ac96a28b46f964/lib/use_packwerk.rb#L68-L69) that might not exist at your company (among other things that don't make sense).

This behavior should be opt-in and configurable. By default the tool should only output things that apply to everyone.

**Comment by edamamez** [comment]
Hi Oleg 👋 !
Thank you for your suggestion, we agree that's a good idea ✅  We will get to it soon!

**Comment by edamamez** [comment]
We also encourage you to open a PR with the change if you feel so empowered! Currently, we only have documentation link configuration, but perhaps we should expand the scope of this and allow configuration of _any and all_ log output... 🤔 

Here is a PR with a similar pattern if you want to go this route: https://github.com/rubyatscale/package_protections/pull/28.

**Comment by alexevanczuk** [comment]
@oleg-vinted This should be configurable for you now! I changed all the defaults to be, as much as possible, Gusto-agnostic. You can also configure `UsePackwerk` to log less/different. Let me know if this works for you or if you would request any further changes 🙏
